interface HtmlProps {
  /** HTML produced at build time by src/lib/markdown.ts. */
  html: string;
  className?: string;
  inline?: boolean;
  id?: string;
}

/**
 * Inserts build-time rendered Markdown. Safe: the pipeline drops raw HTML from the YAML, so
 * this only ever contains markup generated by remark/rehype, KaTeX and Shiki.
 */
export function Html({ html, className, inline = false, id }: HtmlProps) {
  const Tag = inline ? "span" : "div";
  return (
    <Tag
      id={id}
      className={`md ${className ?? ""}`}
      // biome-ignore lint/security/noDangerouslySetInnerHtml: trusted build-time output (no raw HTML from content).
      dangerouslySetInnerHTML={{ __html: html }}
    />
  );
}
